<br><br><br>

### Publications

<br><br>
**Tucker, A.M.**, C.P. McGowan, E. Mulero, N.F. Angeli, J.P. Zegarra. 2020. Developing a demographic projection model to support conservation decision making for an endangered snake with limited monitoring data. Animal Conservation. [pdf](files/Tucker_et_al-2020.pdf)   
  
**Tucker, A.M.**, C.P. McGowan, M. Catalano, A.L. DeRose-Wilson, R.A. Robinson, and J. Zimmerman. 2019. Foraging ecology mediates response to ecological mismatch during migratory stopover. Ecosphere, 10. [pdf](files/Tucker_et_al-2019-Ecosphere.pdf) 
  
**Tucker, A.M.**, C.P. McGowan, R.A. Robinson, J.A. Clark, J.E. Lyons, A.L. DeRose-Wilson, R. du Feu, G.E. Austin, P.W. Atkinson, and N.A. Clark. 2019. Effects of individual misidentification on estimates of survival in long-term mark-resight studies. The Condor: Ornithological Applications, 121: 1-13. [pdf](files/Tucker et al._2019.pdf)   
    
Weaver, R.J., E.A. Santos, **A.M. Tucker**, A.E. Wilson, and G.E. Hill. 2018. Carotenoid metabolism strengthens the link between feather coloration and individual quality. Nature Communications: 9. [pdf](files/Weaver-etal_2018.pdf)  
  
**Tucker, A.M.** and L.P. Bulluck.  2017. No evidence for a negative effect of conspecific brood parasitism on annual survival of female Prothonotary Warblers. Ibis, 160: 447-452. [pdf](files/Tucker-Bulluck_2017.pdf)  
  
**Tucker, A.M.**, R.J. Dyer, S.K. Huber, and L.P. Bulluck. 2016. Opportunistic conspecific brood parasitism in a box-nesting population of Prothonotary Warblers (*Protonotaria citrea*). The Auk: 133, 2, 298-307. [pdf](files/Tucker-etal_2016.pdf)  
  
*In progress*   
  
**Tucker, A.M.** and M.C. Runge. Optimal strategies for managing wildlife harvest under climate change. *In review - Journal of Wildlife Management.*    
  
Dunham, K., **A.M. Tucker**, D. Koons, A. Abebe, F.S. Dobson, and J.B. Grand. Demographic responses to climate change in a threatened Arctic species. *In review - Ecology and Evolution*.  
    
Lawson, A.J., B. Folt, **A.M. Tucker**, F.T. Erickson, and C.P. McGowan. Decision context as a necessary component of population viability analysis appraisal. *In revision - Conservation Biology.*    
  
Folt, B., J.M. Goessling, **A.M.Tucker**, C. Guyer, S. Hermann, E. Shelton-Nix, and C.P. McGowan. Contrasting Patterns of Demography and Population Viability among Six Populations of Gopher Tortoises (*Gopherus polyphemus*) at the Species’ Range Edge. *In revision - Journal of Wildlife Management.*     
  
Valente, J.J., C.L. LeGrande-Rolls, J.W. Rivers, **A.M. Tucker**, R.A. Fisher, and M.G. Betts. The role of conspecific attraction in breeding habitat selection by terrestrial birds: current knowledge and future research directions. *In review - Ornithological Applications*.  
