---
output:
  pdf_document:
    latex_engine: pdflatex
    template: latex-cv.tex
geometry: margin=1in
title: "CV"
author: Anna M. Tucker
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Postdoctoral Research Associate"
address: "USGS Patuxent Wildlife Research Center"
fontawesome: yes
email: annamtucker@gmail.com
github: annamtucker
#phone: "+1 555 5555"
#twitter: annamtucker_
#web: 'annamtucker.github.io'
updated: yes
#keywords: quantitative ecology, population dynamics, migratory birds
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---


# Education

Ph.D. Wildlife Sciences - Auburn University - 2019  
*Stopover ecology and population dynamics of migratory shorebirds*  
Advisor: Dr. Conor McGowan  
  
M.S. Ecology - Virginia Commonwealth University - 2014  
*Occurrence and consequences of conspecific brood parasitism in a cavity-nesting warbler*  
Advisors: Dr. Lesley Bulluck and Dr. Rodney Dyer  
  
B.S. Biology - Loyola University Maryland - 2010  
  
  
# Professional Appointments    
  
Postdoctoral Researcher, U.S. Geological Survey, Patuxent Wildlife Research Center  
Jan 2020-present  
*Time-dependent management strategies for migratory birds under climate change*  
Supervisors: Dr. Michael Runge and Dr. Jim Lyons  
  
Postdoctoral Researcher, School of Forestry and Wildlife Sciences, Auburn University  
Apr 2019-Jan 2020       
*Population analysis and projection modeling for USFWS Species Status Assessments*  
Supervisor: Dr. Conor McGowan  
   
   
# Publications   
  
**Tucker, A.M.**, C.P. McGowan, E. Mulero, N.F. Angeli, J.P. Zegarra. 2020. Developing a demographic projection model to support conservation decision making for an endangered snake with limited monitoring data. Animal Conservation.   
  
**Tucker, A.M.**, C.P. McGowan, M. Catalano, A.L. DeRose-Wilson, R.A. Robinson, and J. Zimmerman. 2019. Foraging ecology mediates response to ecological mismatch during migratory stopover. Ecosphere, 10. 
  
**Tucker, A.M.**, C.P. McGowan, R.A. Robinson, J.A. Clark, J.E. Lyons, A.L. DeRose-Wilson, R. du Feu, G.E. Austin, P.W. Atkinson, and N.A. Clark. 2019. Effects of individual misidentification on estimates of survival in long-term mark-resight studies. The Condor: Ornithological Applications, 121: 1-13.  
    
Weaver, R.J., E.A. Santos, **A.M. Tucker**, A.E. Wilson, and G.E. Hill. 2018. Carotenoid metabolism strengthens the link between feather coloration and individual quality. Nature Communications: 9.
  
**Tucker, A.M.** and L.P. Bulluck.  2017. No evidence for a negative effect of conspecific brood parasitism on annual survival of female Prothonotary Warblers. Ibis, 160: 447-452.
  
**Tucker, A.M.**, R.J. Dyer, S.K. Huber, and L.P. Bulluck. 2016. Opportunistic conspecific brood parasitism in a box-nesting population of Prothonotary Warblers (*Protonotaria citrea*). The Auk: 133, 2, 298-307.
  
*In progress*   
  
**Tucker, A.M.** and M.C. Runge. Optimal strategies for managing wildlife harvest under climate change. *In review - Journal of Wildlife Management.*    
  
Dunham, K., **A.M. Tucker**, D. Koons, A. Abebe, F.S. Dobson, and J.B. Grand. Demographic responses to climate change in a threatened Arctic species. *In review - Ecology and Evolution*.  
    
Lawson, A.J., B. Folt, **A.M. Tucker**, F.T. Erickson, and C.P. McGowan. Decision context as a necessary component of population viability analysis appraisal. *In revision - Conservation Biology.*    
  
Folt, B., J.M. Goessling, **A.M.Tucker**, C. Guyer, S. Hermann, E. Shelton-Nix, and C.P. McGowan. Contrasting Patterns of Demography and Population Viability among Six Populations of Gopher Tortoises (*Gopherus polyphemus*) at the Species’ Range Edge. *In revision - Journal of Wildlife Management.*     
  
Valente, J.J., C.L. LeGrande-Rolls, J.W. Rivers, **A.M. Tucker**, R.A. Fisher, and M.G. Betts. The role of conspecific attraction in breeding habitat selection by terrestrial birds: current knowledge and future research directions. *In review - Ornithological Applications*. 
  
# Research Grants and Fellowships   
  
**2020** Working Group Grant, USGS Powell Center for Earth System Science Analysis and Synthesis* *$170,785*  
**2020** Research Grant, Northeast/Southeast Climate Adaptation Science Center* *$345,904*  
**2019** Co-PI, Research Contract for Species Status Assessments, USFWS Region 2 (pending) *$50,000*  
**2017** Francis M. Peacock Scholarship for Native Bird Habitat, Garden Club of America *$4000*  
**2015** Graduate Thesis/Dissertation Fellowship, Auburn University Graduate School *$500*    
**2015** Research Grant, Eastern Bird Banding Association Memorial Fund *$1000*    
**2013** Student Research Award, VCU Rice Center *$1000*  
**2013** J.J. Murray Research Award, Virginia Society of Ornithology *$1000*    
**2008** Hauber Summer Research Fellowship, Loyola University *$3000*   
\* *not listed as PI but led the writing of these proposals*   
  
# Awards and Honors   
  
**2019** Distinguished Dissertation Award, *Auburn Univeristy Graduate School*  
**2019** Outstanding Doctoral Student, *Auburn University Graduate Student Council*  
**2019** Drummond PhD Student Award, *AU School of Forestry and Wildlife Sciences*  
**2018** Biometrics Working Group Travel Award, *The Wildlife Society*  
**2018** AOS Council Student Presentation Award, *American Ornithological Society*  
**2017** Best Student Poster, *Euring Analytical Meeting and Workshop*  
**2017** Graduate Student Award, *Ducks Unlimited*     
**2014** Outstanding Graduate Student in Ecology, *Virginia Commonwealth University* 
    
# Conference Presentations   
  
## **Invited**  
  
**2019** Encounter type and frequency determine the effects of individual misidentification on survival estimation. *Oral presentation, American Fisheries Society & The Wildlife Society Joint Conference, Reno NV*  
    
## **Contributed**  
  
**2020** A demographic PVA to support conservation decision making for an endangered snake with limited monitoring data. *Oral presentation, The Wildlife Society Annual Meeting, virtual*  
   
**2020** A full annual cycle perspective for analyzing stopover monitoring data: integrated population models for Arctic-breeding shorebirds. *Oral presentation, North American Ornithology Conference* (presented by C.P. McGowan)    
**2019** Estimating population growth rate and latent recruitment at a migratory stopover site using integrated population models. *Oral presentation, American Fisheries Society & The Wildlife Society Joint Conference, Reno NV*  
  
**2019** Annual variation in use of a spring stopover site by three migratory shorebirds. *Oral presentation, American Ornithological Society Annual Meeting, Achorage AK*  
    
**2018** Bias in survival estimates due to individual misidentification in long-term mark-resight studies. *Oral presentation, The Wildlife Society Annual Meeting, Cleveland OH*
  
**2018** Effects of resource mismatch on stopover mass gain dynamics for two Artic-breeding shorebirds. *Oral presentation, American Ornithological Society Annual Meeting, Tucson AZ* Winner--Student Presentation Award
  
**2017** Comparing annual variation in stopover mass gain between two long-distance migrants. *Oral presentation, Western Hemisphere Shorebird Group, Paracas, Peru* (presented by R.A. Robinson)
  
**2017**. Combining multistate models and network theory to evaluate movement patterns during migratory stopover. *Poster presentation, Euring Analytical Meeting, Barcelona, Spain* Winner--Best Student Poster Award
  
**2016** Assessing the influence of migratory connectivity and spring stopover site disturbance on population dynamics using a full annual cycle simulation model. *Oral presentation, North American Ornithological Conference VI, Washington DC*
  
**2014** Conspecific brood parasitism as an alternative breeding strategy in box-nesting Prothonotary Warblers. *Oral presentation, American Ornithologists' Union Annual Meeting, Estes Park CO*
  
**2014** The occurrence and consequences of conspecific brood parasitism in the Prothonotary Warbler (*Protonotaria citrea*).  *Oral presentation, Virginia Society of Ornithology Annual Meeting, Norfolk VA*  
  
  
# Professional Development   
  
Decision Analysis for Natural Resources Certificate Program - NCTC (2020-present)  
Observer, Adaptive Management Review Workshop, Upper Midwest Environmental Science Center *2020*  
Introduction to Bayesian Statistics with Nimble, Reno NV *2019*   
Apprentice, National Conservation Training Center Structured Decision Making Workshop *2018*  
Integrated Population Modeling Workshop, Patuxent Wildlife Research Center *2017*  
Data Integration Workshop, Euring Analytical Meeting, Barcelona *2017*    
Conservation Leaders for Tomorrow, Mansfield GA *2017*  
  
  
# Teaching  
  
## **Lesson Development**  
Quantitative Techniques for Species Status Assessments, USFWS Training Course (2017-2018)  
Wildlife Population Science Lab, Auburn University (Spring 2018)  
Ornithology Program, National Audubon Society Hog Island Family Camp (2017-present)  
Ornithology Lab, Virginia Commonwealth University (Summer 2013)  
  
## **Guest Lectures**  
Avian Conservation in North America, Ornithology, Auburn University (Apr 2018)  
Migratory Shorebirds in Delaware Bay, Osher Lifelong Learning Institute, Auburn AL (Apr 2017)  
Avian Life History, Ornithology, Virginia Commonwealth University (Mar 2014)  
  
## **Teaching Assistantships**  
Ornithology Lab, Auburn University (Spring 2016)  
Anatomy and Physiology II Lab, Auburn University (Spring 2015-Fall 2016)  
Ornithology Lab, Virginia Commonwealth University (Spring 2014)  
Tropical Avian Ecology in Panama, Virginia Commonwealth University (Spring 2014)  
Intro. to Biological Sciences Lab, Virginia Commonwealth University (Fall 2012-Fall 2013)   
  
  
# Service and Outreach  
Peer Reviewer: *Ibis*, *Conservation Science and Practice*, *Landscape and Urban Planning*, *Urban Ecosystems*, *Evolutionary Ecology*   
Founder and Coordinator, Wildlife Graduate Student & Postdoc Quant Club (2017-2018)  
Graduate Student Representative, IT Specialist Hiring Committee (Jan 2018)  
Ornithology Instructor, National Audubon Society, Hog Island Family Camp (2017-present)  
Instructor, Graduate Women in Science and Girl Scout Pi Day (Mar 2017)  
Ornithology Instructor, Alabama Extension Master Naturalist Program (Dec 2016)  
Bird Survey Leader, Alabama Extension Program BioBlitz (2016-2017)  
Poster Session Judge, Auburn University This is Research Symposium (Mar 2016)  
Shorebird Monitoring Volunteer, Delaware Shorebird Project (2015-2018)  
Vice President, VCU Graduate Organization of Biology Students (2013-2014)  
Interpretive Aide, National Aquarium in Baltimore (2010-2011)  
Environmental Education Volunteer, Patterson Park Audubon Society (2009-2010)  